fun main(){
    // Behebe die Exception
    var test:String= "Hallo Welt"
    var test2:Int= test.toInt()
    println(test2)
}